version: "3"
services:
  redis:
    image: redis
    # restart: always
    ports:
      - 6379:6379
    networks:
      - capstone

  mongo:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: capstone
      MONGO_INITDB_ROOT_PASSWORD: capstone
      MONGO_INITDB_DATABASE: capstoneBackend
    volumes:
      - ./mocks:/docker-entrypoint-initdb.d
      ## uncomment to save mongodb data locally
      # - ./mongo_data:/data/db
    networks:
      - capstone

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: capstone
      ME_CONFIG_MONGODB_ADMINPASSWORD: capstone
      ME_CONFIG_MONGODB_URL: mongodb://capstone:capstone@mongo:27017/
    networks:
      - capstone
    depends_on:
      - mongo

networks:
  capstone:
    name: capstone
    driver: bridge
